openapi: 3.0.0
info:
  title: Student Management System API
  description: API documentation for managing students in the Student Management System
  version: 1.0.0

paths:
  /students:
    get:
      summary: Get a list of all students
      operationId: listStudents
      responses:
        '200':
          description: A list of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StudentDto'
    post:
      summary: Create a new student
      operationId: createStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentDto'
      responses:
        '201':
          description: Student created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDto'

  /students/{studentId}:
    get:
      summary: Get a student by ID
      operationId: getStudentById
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Student found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDto'
        '404':
          description: Student not found
    put:
      summary: Update an existing student
      operationId: updateStudent
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentDto'
      responses:
        '200':
          description: Student updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDto'

  /students/{studentId}/delete:
    delete:
      summary: Delete a student by ID
      operationId: deleteStudent
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Student deleted successfully

components:
  schemas:
    StudentDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true  # id is auto-generated and not required from user input
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
      required:
        - firstName
        - lastName
        - email
